# Generated by Django 2.2.11 on 2020-06-26 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dosa', '0003_auto_20200623_2019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='MOQ',
        ),
        migrations.AddField(
            model_name='product',
            name='Availability',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Packaging',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Type',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='box_dimension',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size_or_weight',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ProductVoting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_vote', models.IntegerField(default=0)),
                ('yes', models.IntegerField(default=0)),
                ('no', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dosa.Product')),
            ],
        ),
    ]
