# Generated by Django 2.2.11 on 2020-06-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dosa', '0007_auto_20200628_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Availability',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='Packaging',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='Type',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='box_dimension',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_or_weight',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='youtube_link',
            field=models.TextField(),
        ),
    ]
